"""empty message

Revision ID: 668dba03c6e1
Revises: 53c3af72fb23
Create Date: 2021-03-05 17:12:12.036889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '668dba03c6e1'
down_revision = '53c3af72fb23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('created_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'created_date')
    # ### end Alembic commands ###
